### ISSUE TITLE
Endpoint and Authorization Key

### ISSUE THREAD

**Issue by AndrewHoh** [bweldy1/GolfMajors#1]
Hi bweldy1,

I just wanted to let you know that your DocumentDB endpoint and authorization key is publicly exposed. You may want to separate the config files into a separate non-committed config file. You can find examples here: https://github.com/Azure-Samples/documentdb-dotnet-getting-started. For extra security, you can also rotate your keys in the Azure portal: https://portal.azure.com.

Best,
Andy

**Comment by bweldy1** [comment]
thanks for taking the time to comment.  that was just me being lazy, which is a horrible excuse for something so simple.

i have disabled the old key and change the way it is loaded.
